language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "8"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm run-script test-travis"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"